version: '3.8'
services:
  mysql:
    image: "mysql"
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "r00t_p455w0rd"
      MYSQL_DATABASE: "transactions"